services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      # Mapeia a porta externa (do .env) para a porta interna 5000 do container.
      - "${FLASK_RUN_PORT}:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    # Comando do worker atualizado para o formato JSON, mais robusto.
    command: ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
